### ISSUE TITLE
Script in a rule for setting the widget enable property does set the else case properly.

### ISSUE THREAD

**Issue by tauferg** [kasemir/org.csstudio.display.builder#488] opened 2019-01-11 16:16 UTC
In generating a rule to set the enable state of a widget, in this instance based upon the pvInt value of another widget, sets both the conditional (if) and non-conditional (else) states of the enable property to "true" rather than "true" and "false".

Steps:
    - Create a rule.  Enter a name for the rule (Enable).
    - Select 'enabled' in the Property ID: drop down.
    - Add a PV in the PV Table
    - Add a condition in the Expressions Table.
    - View the script by clicking on the Show Script button.

![image](https://user-images.githubusercontent.com/29707791/51045752-5bbc8200-1592-11e9-9eeb-0359fa8e0fca.png)

**Comment by kasemir** [comment] 2019-01-11 16:53
That's by design.
The "else" case is always the default state, i.e. what you set on the property.

Create a new widget, it's "enabled" property is true.
Create a rule for "enabled", it will always end with "else: .. enabled = true".

You can either

a) Set the enabled property to false, and then in your rule add conditions to make it true.

b) Keep your rule settings, but set the enabled property to false.

**Comment by kasemir** [comment] 2019-01-17 20:09
Closing this because it's not a bug but exactly as it's meant to be.

**Closed by kasemir** 2019-01-17 20:09 UTC
