### ISSUE TITLE
BOY XYGraph vs. XYPlot and Data Browser plots

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#243] opened 2017-06-14 13:48 UTC
I have a simple BOY OPI using the XYGraph plotting a simulated PV:

<img width="561" alt="boy-xygraph" src="https://user-images.githubusercontent.com/10833922/27135342-961f002a-5118-11e7-92c6-25a894af09d2.png">
<img width="290" alt="boy-xygraph-properties" src="https://user-images.githubusercontent.com/10833922/27135347-98f23a10-5118-11e7-967e-8069f070b6de.png">

When I load it with Display Builder it doesn't work as expected:

<img width="561" alt="db-xyplot" src="https://user-images.githubusercontent.com/10833922/27135418-ba2e7cd4-5118-11e7-89d5-141f99e50bbd.png">
<img width="291" alt="db-xyplotproperties" src="https://user-images.githubusercontent.com/10833922/27135422-bbb90042-5118-11e7-96a9-b8219f4d060f.png">

So these are hte questions:

- How the Display Builder's XY-Plot must be configured to show a simple PV value changing in time?
- Why the conversion from BOY's XYGraph doesn't work?

**Comment by kasemir** [comment] 2017-06-14 16:12
The BOY XYPlot handles some fundamentally difference cases. It can plot a scalar over time or index, using its own buffer to assemble the waveform from received samples. Like the Data Browser, but without archive access.

Or it can plot waveforms: A 'Y' waveform over 0..len-1, or a 'Y' waveform over an 'X' waveform.

The display builder uses the data browser widget for scalar-over-time, and the XYPlot for Y-waveform-over-index or Y-waveform-over-X-waveform. Plus it adds an optional error bar waveform.

What's missing:
XYPlot could try to detect that a legacy XYGraph has Plot Mode: plot last N points and a buffer size, and convert that into a Data Browser widget. I'll look at that.

**Comment by kasemir** [comment] 2017-06-14 16:44
Not sure how to distinguish at edit-time.

A BOY XYGraph may have PV: 'abc', Plot Mode: 'last N points', buffer size: 100.
If the PV turns out to be a scalar, it will add received samples to a 100-element buffer and plot that waveform.

![xy](https://user-images.githubusercontent.com/1932421/27143937-10530370-50fe-11e7-8984-fb15d5e445b1.png)

In the screenshot, the steps in the blue line are a result of the way BOY handles the received values on the UI thread and gets behind. Doesn't tend to happen in the data browser.
The disconnect in the grid lines is the result of the screenshot utility capturing two different screen refreshes.


On the other hand, if the PV turns out to provide array samples, the Plot Mode and Buffer Size are ignored, and instead the waveform is plotted over 0..(len-1).

By design the editor doesn't have any runtime knowledge. When editing a file, one might in fact not be able to connect to the control system. So I don't see a way to automatically convert plots, and we're back to what has been said about the Display Builder from the start: Most plots and scripts will require manual adjustments. XYGraphs are converted into XYPlots, which works for most waveform PVs. Data browser widgets are converted into the same, which was always a better option for scalar PVs. XYGraphs that plotted scalar PVs over array index ( why would one want to do that? ) won't convert.

**Comment by kasemir** [comment] 2017-06-14 18:17
I've added a log message and an example, but again not clear how to auto-convert XYPlots that should really have been Data Browser widgets.

**Comment by claudio-rosati** [comment] 2017-06-15 07:19
OK, understood.

The only thing is still unclear to me is how to specify the sinvgle PV name to the Data Browser widget: It seems to me that only a file can be given. Moreover there is no Data Browser example.

**Comment by kasemir** [comment] 2017-06-15 14:05
Yes, needs a *.plt file to configure not just the PV but also archive data sources etc.
I've added an example.

**Comment by claudio-rosati** [comment] 2017-06-15 14:19
I have a problem with the example, when I open the `plots_databrowser.bob` the Databrowser area is white and the following appears in console:

```
2017-06-15 16:19:31.095 WARNING [Thread 53] org.csstudio.display.builder.model.persist.ModelReader (readWidgetsAllowingRetry) - Unknown widget type 'databrowser', line 49
```

**Comment by kasemir** [comment] 2017-06-15 14:29
That's why there was originally no example ;-) . I figured the display builder examples should be limited to what you always get, not include optional widgets that might only exist at one site but not another.

The data browser widget for the display builder is optional, because it depends, as you might have guessed, on having the data browser.
In your product, you need to include
 * org.csstudio.trends.databrowser3 - The standalone databrowser
 * org.csstudio.trends.databrowser3.bobwidget - The databrowser widget for the display builder
 * org.csstudio.trends.databrowser3.opiwidget - The databrowser widget for BOY (if  you want)

At the same time, remove all org.csstudio.trends.databrowser2* plugins.

When the data browser widget is included, you should see it listed in the editor palette under "Plots".
Note this only works in CSS, not in the standalone editor or runtime because the standalone display builder editor and runtime has just the display builder, not the data browser.

**Comment by claudio-rosati** [comment] 2017-06-15 14:48
I've discovered that my compiled product worked, but not the if run fromEclipse: I've missed to enable databrowser3 on my Runtime Configuration.

Thank you for the help.

**Comment by kasemir** [comment] 2018-06-15 02:58
Repeated in #391, closing this one.

**Closed by kasemir** 2018-06-15 02:58 UTC
