### ISSUE TITLE
Problems using DataBrowser 3 in Display Builder

### ISSUE THREAD

**Issue by claudio-rosati** [kasemir/org.csstudio.display.builder#521] opened 2019-03-26 10:56 UTC
I have a problem related to a long wait time when starting CS-Studio in control room where it is supposed to open an OPI containing a DataBrowser widget.

Here are the exceptions I've received from the operator:

[CSReport.txt](https://github.com/kasemir/org.csstudio.display.builder/files/3007770/CSReport.txt)

**Comment by kasemir** [comment] 2019-03-26 12:14
Duplicate of #462

**Closed by kasemir** 2019-03-26 12:14 UTC
Labels: bug, help wanted

**Comment by claudio-rosati** [comment] 2019-03-26 12:24
Thank you Kay. For some reasons I've lost the link to #462.
I've now asked the operator to delete the `.metadata` folder. If it works I'll close #462 too.

**Comment by kasemir** [comment] 2019-03-26 12:30
That's of course a workaround, not a solution, but at this time I don't have a better solution.
